#!/bin/bash
##### DO NOT EDIT BY HAND This is generated by maven #########
CLASSPATH=.:${project.build.finalName}.jar
MAIN_CLASS=org.imirsel.nema.flowservice.FlowServiceApp
CWD=`pwd`
HOST=${nema.deployment.hostname}
FLAG="-Dava.rmi.server.logCalls=true -Djava.rmi.server.codebase=file:///$CWD/lib -Djava.rmi.server.hostname=$HOST -Djava.util.logging.config.file=logging.properties"
mkdir -p log
jarList=`find $CWD/lib -name '*.jar'`

for X in $jarList
do
  CLASSPATH=$CLASSPATH":"$X
done

CLASSPATH=$CLASSPATH":."

nohup java -Xmx1024M -classpath $CLASSPATH $FLAG $MAIN_CLASS 2>&1 > log/flowservice.log &


echo "tail -f log/flowservice.log to view the logs"
#echo "java -classpath $CLASSPATH $FLAG $MAIN_CLASS"
