#!/bin/bash
##### DO NOT EDIT BY HAND This is generated by maven #########
CLASSPATH=.:${project.build.finalName}.jar
MAIN_CLASS=org.imirsel.nema.flowservice.FlowServiceApp
CWD=`pwd`
FLAG="-Dava.rmi.server.logCalls=true -Djava.rmi.server.codebase=file:///$CWD/lib -Djava.rmi.server.hostname=nema.lis.uiuc.edu -Djava.util.logging.config.file=logging.properties"
mkdir -p log
jarList=`find $CWD/lib -name '*.jar'`

for X in $jarList
do
  CLASSPATH=$CLASSPATH":"$X
done

CLASSPATH=$CLASSPATH":."

java -Xmx1024M -classpath $CLASSPATH $FLAG $MAIN_CLASS
