<%-- 
    Document   : index
    Created on : May 19, 2011, 2:42:57 PM
    Author     : gzhu1
--%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core"  prefix="c" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>SALAMI: Structural Segmentation Experiments</title>

        <LINK REL=StyleSheet HREF="support/menu.css" TYPE="text/css" />
        <LINK REL=StyleSheet HREF="support/tableblue.css" TYPE="text/css" />

        <script type="text/javascript" src="support/jquery.min.js"></script>


    </head>

    <body>

        <table id="h2table">
            <tr>
                <td><img src="support/logo.png" width="160"></td>
                <td><h2>SALAMI: Structural Segmentation Experiments</h2></td>
            </tr>
        </table>

        <div id="tabs">
            <ul>
                <li><a href="index.jsp" title="summary"><span>Summary</span></a></li>
                <li class="shown"><a href="comparison.jsp" title="comparison"><span>Comparison</span></a></li>
                <li><a href="classical.jsp" title="classical"><span>Classical</span></a></li>
                <li><a href="jazz.jsp" title="Jazz"><span>Jazz</span></a></li>
                <li><a href="live.jsp" title="Live"><span>Live</span></a></li>
                <li><a href="pop.jsp" title="Pop"><span>Popular</span></a></li>
                <li><a href="world.jsp" title="World"><span>World</span></a></li>
                <li><a href="help.jsp" title="help"><span>Help</span></a></li>
            </ul>
        </div>

        <br><a name="top"></a>
            <div id="content">
                <h2>Algorithm Evaluation</h2>




                <h3>1. DATASETS</h3>


                <table>
                    <thead>
                        <tr>
                            <th>
                                Style
                            </th>
                            <th>
                                Double-keyed
                            </th>
                            <th>
                                Single-keyed
                            </th>
                            <th>
                                Total
                            </th>
                            <th>
                                Percentage
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            Classical
                        </td>
                        <td>
                            159
                        </td>
                        <td>
                            66
                        </td>
                        <td>
                            225
                        </td>
                        <td>
                            16%
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Jazz
                        </td>
                        <td>
                            225
                        </td>
                        <td>
                            12
                        </td>
                        <td>
                            237
                        </td>
                        <td>
                            17%
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Popular
                        </td>
                        <td>
                            205
                        </td>
                        <td>
                            117
                        </td>
                        <td>
                            322
                        </td>
                        <td>
                            23%
                        </td>
                    </tr>
                    <tr>
                        <td>
                            World
                        </td>
                        <td>
                            186
                        </td>
                        <td>
                            31
                        </td>
                        <td>
                            217
                        </td>
                        <td>
                            16%
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Live
                        </td>
                        <td>
                            273
                        </td>
                        <td>
                            109
                        </td>
                        <td>
                            382
                        </td>
                        <td>
                            28%
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Total</b>
                        </td>
                        <td>
                            <b>1048</b>
                        </td>
                        <td>
                            <b>335</b>
                        </td>
                        <td>
                            <b>1383</b>
                        </td>
                        <td>
                            100%
                        </td>
                    </tr>
                </table>
                
                <p><b>Table 1.</b><span> Breakdown of the MRX10V2 structure
                        segmentation dataset by musical style</span></p>



                <h3>2.   ALGORITHMS</h3>

                <table>
                    <thead
                        <tr>
                            <th>
                                Algorithms
                            </th>
                            <th>
                                Average processing time (min. / piece)
                            </th>
                        </tr>
                        <tr>
                            <td>
                                WB1 
                            </td>
                            <td>
                                2.28
                            </td>
                        </tr>
                        <tr>
                            <td>
                                GP7 
                            </td>
                            <td>
                                2.64
                            </td>
                        </tr>
                    </thead>
                    <tr>

                        <td>
                            BV1 &amp; BV2 
                        </td>
                        <td>
                            2.94
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            5.60
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2 
                        </td>
                        <td>
                            6.38
                        </td>
                    </tr>
                </table>
                <p><b>Table 2.</b><span> Algorithm names, corresponding
                        references, and runtimes.</span></p>


                <h3>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Evaluation</h3>

                <table>
                    <thead>
                        <tr>
                            <th>
                                (a)
                                Algorithm
                            </th>
                            <th>
                                NCE-OSS
                            </th>
                            <th>
                                NCE-USS
                            </th>
                            <th>
                                FPC-F
                            </th>
                            <th>
                                FPC-P
                            </th>
                            <th>
                                FPC-R
                            </th>
                            <th>
                                RCI
                            </th>
                            <th>
                                SBR-F@0.5s
                            </th>
                            <th>
                                SBR-P@0.5s
                            </th>
                            <th>
                                SBR-R@0.5s
                            </th>
                            <th>
                                SBR-F@3s
                            </th>
                            <th>
                                SBR-P@3s
                            </th>
                            <th>
                                SBR-R@3s
                            </th>
                            <th>
                                AB-2-RB
                            </th>
                            <th>
                                RB-2-AB
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            BV1
                        </td>
                        <td>
                            0.605
                        </td>
                        <td>
                            0.441
                        </td>
                        <td>
                            0.520
                        </td>
                        <td>
                            0.513
                        </td>
                        <td>
                            0.669
                        </td>
                        <td>
                            0.549
                        </td>
                        <td>
                            0.190
                        </td>
                        <td>
                            0.151
                        </td>
                        <td>
                            0.289
                        </td>
                        <td>
                            0.450
                        </td>
                        <td>
                            0.361
                        </td>
                        <td>
                            0.669
                        </td>
                        <td>
                            1.797
                        </td>
                        <td>
                            7.554
                        </td>
                    </tr>
                    <tr>
                        <td>
                            BV2
                        </td>
                        <td>
                            0.454
                        </td>
                        <td>
                            0.715
                        </td>
                        <td>
                            0.427
                        </td>
                        <td>
                            0.678
                        </td>
                        <td>
                            0.350
                        </td>
                        <td>
                            0.638
                        </td>
                        <td>
                            0.189
                        </td>
                        <td>
                            0.150
                        </td>
                        <td>
                            0.286
                        </td>
                        <td>
                            0.449
                        </td>
                        <td>
                            0.361
                        </td>
                        <td>
                            0.666
                        </td>
                        <td>
                            1.812
                        </td>
                        <td>
                            7.552
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GP7
                        </td>
                        <td>
                            0.499
                        </td>
                        <td>
                            0.683
                        </td>
                        <td>
                            0.485
                        </td>
                        <td>
                            0.675
                        </td>
                        <td>
                            0.424
                        </td>
                        <td>
                            0.654
                        </td>
                        <td>
                            0.188
                        </td>
                        <td>
                            0.146
                        </td>
                        <td>
                            0.306
                        </td>
                        <td>
                            0.440
                        </td>
                        <td>
                            0.346
                        </td>
                        <td>
                            0.695
                        </td>
                        <td>
                            2.073
                        </td>
                        <td>
                            6.634
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2
                        </td>
                        <td>
                            0.546
                        </td>
                        <td>
                            0.591
                        </td>
                        <td>
                            0.559
                        </td>
                        <td>
                            0.617
                        </td>
                        <td>
                            0.583
                        </td>
                        <td>
                            0.659
                        </td>
                        <td>
                            0.195
                        </td>
                        <td>
                            0.218
                        </td>
                        <td>
                            0.197
                        </td>
                        <td>
                            0.435
                        </td>
                        <td>
                            0.485
                        </td>
                        <td>
                            0.440
                        </td>
                        <td>
                            7.262
                        </td>
                        <td>
                            5.338
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            0.624
                        </td>
                        <td>
                            0.625
                        </td>
                        <td>
                            0.556
                        </td>
                        <td>
                            0.649
                        </td>
                        <td>
                            0.586
                        </td>
                        <td>
                            0.662
                        </td>
                        <td>
                            0.291
                        </td>
                        <td>
                            0.302
                        </td>
                        <td>
                            0.326
                        </td>
                        <td>
                            0.470
                        </td>
                        <td>
                            0.479
                        </td>
                        <td>
                            0.534
                        </td>
                        <td>
                            8.565
                        </td>
                        <td>
                            5.389
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WB1
                        </td>
                        <td>
                            0.609
                        </td>
                        <td>
                            0.540
                        </td>
                        <td>
                            0.546
                        </td>
                        <td>
                            0.583
                        </td>
                        <td>
                            0.608
                        </td>
                        <td>
                            0.630
                        </td>
                        <td>
                            0.237
                        </td>
                        <td>
                            0.240
                        </td>
                        <td>
                            0.272
                        </td>
                        <td>
                            0.393
                        </td>
                        <td>
                            0.395
                        </td>
                        <td>
                            0.446
                        </td>
                        <td>
                            10.780
                        </td>
                        <td>
                            3.881
                        </td>
                    </tr>

                    <thead>
                        <tr>
                            <th>
                                (b)
                                Algorithm
                            </th>
                            <th>
                                NCE-OSS
                            </th>
                            <th>
                                NCE-USS
                            </th>
                            <th>
                                FPC-F
                            </th>
                            <th>
                                FPC-P
                            </th>
                            <th>
                                FPC-R
                            </th>
                            <th>
                                RCI
                            </th>
                            <th>
                                SBR-F@0.5s
                            </th>
                            <th>
                                SBR-P@0.5s
                            </th>
                            <th>
                                SBR-R@0.5s
                            </th>
                            <th>
                                SBR-F@3s
                            </th>
                            <th>
                                SBR-P@3s
                            </th>
                            <th>
                                SBR-R@3s
                            </th>
                            <th>
                                AB-2-RB
                            </th>
                            <th>
                                RB-2-AB
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            BV1
                        </td>
                        <td>
                            0.643
                        </td>
                        <td>
                            0.323
                        </td>
                        <td>
                            0.384
                        </td>
                        <td>
                            0.321
                        </td>
                        <td>
                            0.680
                        </td>
                        <td>
                            0.505
                        </td>
                        <td>
                            0.179
                        </td>
                        <td>
                            0.236
                        </td>
                        <td>
                            0.159
                        </td>
                        <td>
                            0.567
                        </td>
                        <td>
                            0.744
                        </td>
                        <td>
                            0.499
                        </td>
                        <td>
                            2.905
                        </td>
                        <td>
                            2.007
                        </td>
                    </tr>
                    <tr>
                        <td>
                            BV2
                        </td>
                        <td>
                            0.521
                        </td>
                        <td>
                            0.567
                        </td>
                        <td>
                            0.373
                        </td>
                        <td>
                            0.452
                        </td>
                        <td>
                            0.386
                        </td>
                        <td>
                            0.712
                        </td>
                        <td>
                            0.177
                        </td>
                        <td>
                            0.234
                        </td>
                        <td>
                            0.157
                        </td>
                        <td>
                            0.565
                        </td>
                        <td>
                            0.741
                        </td>
                        <td>
                            0.497
                        </td>
                        <td>
                            2.937
                        </td>
                        <td>
                            1.980
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GP7
                        </td>
                        <td>
                            0.584
                        </td>
                        <td>
                            0.557
                        </td>
                        <td>
                            0.432
                        </td>
                        <td>
                            0.467
                        </td>
                        <td>
                            0.482
                        </td>
                        <td>
                            0.720
                        </td>
                        <td>
                            0.163
                        </td>
                        <td>
                            0.208
                        </td>
                        <td>
                            0.153
                        </td>
                        <td>
                            0.472
                        </td>
                        <td>
                            0.605
                        </td>
                        <td>
                            0.436
                        </td>
                        <td>
                            4.946
                        </td>
                        <td>
                            2.300
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2
                        </td>
                        <td>
                            0.599
                        </td>
                        <td>
                            0.442
                        </td>
                        <td>
                            0.440
                        </td>
                        <td>
                            0.395
                        </td>
                        <td>
                            0.615
                        </td>
                        <td>
                            0.655
                        </td>
                        <td>
                            0.124
                        </td>
                        <td>
                            0.276
                        </td>
                        <td>
                            0.087
                        </td>
                        <td>
                            0.356
                        </td>
                        <td>
                            0.776
                        </td>
                        <td>
                            0.253
                        </td>
                        <td>
                            11.311
                        </td>
                        <td>
                            1.885
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            0.666
                        </td>
                        <td>
                            0.478
                        </td>
                        <td>
                            0.435
                        </td>
                        <td>
                            0.426
                        </td>
                        <td>
                            0.609
                        </td>
                        <td>
                            0.635
                        </td>
                        <td>
                            0.200
                        </td>
                        <td>
                            0.376
                        </td>
                        <td>
                            0.150
                        </td>
                        <td>
                            0.415
                        </td>
                        <td>
                            0.749
                        </td>
                        <td>
                            0.314
                        </td>
                        <td>
                            13.944
                        </td>
                        <td>
                            1.835
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WB1
                        </td>
                        <td>
                            0.675
                        </td>
                        <td>
                            0.420
                        </td>
                        <td>
                            0.442
                        </td>
                        <td>
                            0.382
                        </td>
                        <td>
                            0.653
                        </td>
                        <td>
                            0.632
                        </td>
                        <td>
                            0.148
                        </td>
                        <td>
                            0.277
                        </td>
                        <td>
                            0.112
                        </td>
                        <td>
                            0.317
                        </td>
                        <td>
                            0.588
                        </td>
                        <td>
                            0.239
                        </td>
                        <td>
                            16.031
                        </td>
                        <td>
                            1.975
                        </td>
                    </tr>
                </table>

                <p><b>Table 3.</b><span> Evaluations against coarse (a)
                        and fine (b) ground truth annotations.</span></p>



                <h3>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    Results</h3>

                <table>
                    <thead>
                        <tr>
                            <th>
                                Algorithm
                            </th>
                            <th>
                                MIREX10
                            </th>
                            <th>
                                MIREX09
                            </th>
                            <th>
                                MRX10V2
                            </th>
                            <th>
                                Ave.
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            BV1
                        </td>
                        <td>
                            0.520
                        </td>
                        <td>
                            0.502
                        </td>
                        <td>
                            0.520
                        </td>
                        <td>
                            0.514
                        </td>
                    </tr>
                    <tr>
                        <td>
                            BV2
                        </td>
                        <td>
                            0.531
                        </td>
                        <td>
                            0.493
                        </td>
                        <td>
                            0.427
                        </td>
                        <td>
                            0.484
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GP7
                        </td>
                        <td>
                            0.592
                        </td>
                        <td>
                            0.536
                        </td>
                        <td>
                            0.485
                        </td>
                        <td>
                            0.538
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2
                        </td>
                        <td>
                            0.600
                        </td>
                        <td>
                            0.555
                        </td>
                        <td>
                            0.559
                        </td>
                        <td>
                            0.571
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            0.625
                        </td>
                        <td>
                            0.613
                        </td>
                        <td>
                            0.556
                        </td>
                        <td>
                            <b>0.598</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WB1
                        </td>
                        <td>
                            0.602
                        </td>
                        <td>
                            0.544
                        </td>
                        <td>
                            0.546
                        </td>
                        <td>
                            0.564
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Ave.
                        </td>
                        <td>
                            <b>0.578</b>
                        </td>
                        <td>
                            0.541
                        </td>
                        <td>
                            0.516
                        </td>
                        <td>
                            0.545
                        </td>
                    </tr>
                </table>


                <p><b><span>Table
                            4a.  </span></b>Comparison of algorithms over datasets<b></b></p>



                <table>
                    <thead>
                        <tr>
                            <th>
                                Algorithm
                            </th>
                            <th>
                                Live
                            </th>
                            <th>
                                Classical
                            </th>
                            <th>
                                Jazz
                                </td>
                                <th>
                                    Popular
                                </th>
                                <th>
                                    World
                                </th>
                                <th>
                                    Ave.
                                </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            BV1
                        </td>
                        <td>
                            0.504
                        </td>
                        <td>
                            0.513
                        </td>
                        <td>
                            0.544
                        </td>
                        <td>
                            0.519
                        </td>
                        <td>
                            0.521
                        </td>
                        <td>
                            0.520
                        </td>
                    </tr>
                    <tr>
                        <td>
                            BV2
                        </td>
                        <td>
                            0.432
                        </td>
                        <td>
                            0.426
                        </td>
                        <td>
                            0.398
                        </td>
                        <td>
                            0.451
                        </td>
                        <td>
                            0.439
                        </td>
                        <td>
                            0.429
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GP7
                        </td>
                        <td>
                            0.510
                        </td>
                        <td>
                            0.427
                        </td>
                        <td>
                            0.475
                        </td>
                        <td>
                            0.513
                        </td>
                        <td>
                            0.484
                        </td>
                        <td>
                            0.482
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            0.532
                        </td>
                        <td>
                            0.564
                        </td>
                        <td>
                            0.574
                        </td>
                        <td>
                            0.574
                        </td>
                        <td>
                            0.545
                        </td>
                        <td>
                            0.558
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2
                        </td>
                        <td>
                            0.557
                        </td>
                        <td>
                            0.590
                        </td>
                        <td>
                            0.556
                        </td>
                        <td>
                            0.543
                        </td>
                        <td>
                            0.555
                        </td>
                        <td>
                            0.560
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WB1
                        </td>
                        <td>
                            0.560
                        </td>
                        <td>
                            0.524
                        </td>
                        <td>
                            0.547
                        </td>
                        <td>
                            0.548
                        </td>
                        <td>
                            0.537
                        </td>
                        <td>
                            0.543
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Ave.
                        </td>
                        <td>
                            0.516
                        </td>
                        <td>
                            0.507
                        </td>
                        <td>
                            0.516
                        </td>
                        <td>
                            0.525
                        </td>
                        <td>
                            0.514
                        </td>
                        <td>
                            0.515
                        </td>
                    </tr>
                    
                </table>
                <br/>
                <b>Table 4b</b>. Results by musical style


                <br/>

               <br/>



                <table>
                    <thead>
                        <tr>
                            <th>
                                Algorithm
                            </th>
                            <th>
                                Fine
                            </th>
                            <th>
                                Coarse
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            BV1
                        </td>
                        <td>
                            0.392
                        </td>
                        <td>
                            0.5248
                        </td>
                    </tr>
                    <tr>
                        <td>
                            BV2
                        </td>
                        <td>
                            0.371
                        </td>
                        <td>
                            0.4338
                        </td>
                    </tr>
                    <tr>
                        <td>
                            GP7
                        </td>
                        <td>
                            0.4332
                        </td>
                        <td>
                            0.4848
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MHRAF2
                        </td>
                        <td>
                            0.4477
                        </td>
                        <td>
                            0.5647
                        </td>
                    </tr>
                    <tr>
                        <td>
                            MND1
                        </td>
                        <td>
                            0.4423
                        </td>
                        <td>
                            0.559
                        </td>
                    </tr>
                    <tr>
                        <td>
                            WB1
                        </td>
                        <td>
                            0.4491
                        </td>
                        <td>
                            0.5522
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Human
                        </td>
                        <td>
                            0.6289
                        </td>
                        <td>
                            0.7211
                        </td>
                    </tr>
                </table>

               <br/>

                <b>Table 4c.</b> Fined-grained vs. coarse-grained FPC-F results.

                

                <p><a href="img/fig4a.png"><img width="700" src="img/fig4a.png" ></a></p>

                <p style="width: 800px;"><b>Figure 4a.</b>
                        Tukey-Kramer HSD comparison plots of the human and algorithm mean performance ranks across 794 double-keyed tracks. Circles indicate the groups. The members of each group are statistically significantly different than the other groups.</p>



                

                <p><a href="img/fig4b.png"><img width="700" src="img/fig4b.png" ></a></p>

                <p style="width: 800px;"><b>Figure 4b.</b><span>
                        Tukey-Kramer HSD comparison plots of each musical style's mean performance  ranks across algorithms. There is no statistically significant difference. Algorithms performed equally well across different musical styles.</span></p>
                
                

                

                <p><a href="img/fig4c.png"><img width="700" src="img/fig4c.png" ></a></p>

                <p style="width: 800px;"><b>Figure 4c.</b><span>
                        Tukey-Kramer HSD comparison plots of each dataset's mean performance  ranks across algorithms. Algorithms performed better on MIREX10 dataset which consists of tracks from the RWC database.</span></p>


            </div>
    </body>
</html>
